### ISSUE TITLE
Copy:  inconsistency in the registration form

### ISSUE THREAD

**Issue by BrunoGameiro** [antoniojps/voluntarios#18]
In the registration form I think that the topic related to the area of ​​interest should also have a question, because all the other topics have questions.
This is the only one that has:
- title "area of ​​interest"
- subtitle "where can you help?".
Only in the topics related to email and password should it be "Insere o teu email", "define a tua palavra-chave".

In addition, we must establish a standard for questions:
- "Qual a sua ocupação/profissão?"
- "Qual é o seu primeiro nome?"
We should write with "é" or not.

We treat volunteers with "Tu" or "Você".

**Comment by antoniojps** [comment]
I went with:

1. Quais são as tuas áreas de interesse?
2. Qual é a tua ocupação/profissão?
3. Onde tens possibilidade de ajudar?
4. Qual é o teu primeiro nome?
5. Qual é o teu último nome?
6. Insere o teu email
7. Define a tua palavra-chave

I think we should treat them as "Tu", that's our spirit.

**Comment by BrunoGameiro** [comment]
For me it's ok! That was the idea
