### ISSUE TITLE
Bug: locations filters not working correctly

### ISSUE THREAD

**Issue by antoniojps** [antoniojps/voluntarios#4]
Find out why locations filters is messed up.

**Comment by vascosilvaa** [comment]
Hey @antoniojps . Can you check if you get the correct behaviour now?
Deployed a fix. Thanks

**Comment by antoniojps** [comment]
Hey @vascosilvaa. I believe this has to do with the backend. I will investigate further and let you know if it's fixed before closing it.

**Comment by vascosilvaa** [comment]
Thanks for the feedback @antoniojps

**Comment by antoniojps** [comment]
Hey @vascosilvaa  We might have to release without some filters, but I will try my best to figure out what's going on.

**Comment by antoniojps** [comment]
https://github.com/antoniojps/voluntarios/commit/a2558baf8ffc20762996bc76dc5b844bc184e427

Ended up having to downgrade to [mongoo-paginate](vhttps://www.npmjs.com/package/mongoose-paginate) instead of [mongoose-paginate-v2](https://www.npmjs.com/package/mongoose-paginate-v2) in order to support [$nearSphere](https://docs.mongodb.com/manual/reference/operator/query/nearSphere/) queries.

Related:
https://github.com/aravindnc/mongoose-paginate-v2/issues/42#issuecomment-606877450
